[mcp_servers.gitkraken]
command = "gk"
args = ["mcp"]

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "YOUR_API_KEY"]
command = "npx"

[projects."/workspaces/rando-tde"]
trust_level = "trusted"
